### ISSUE TITLE
Can't export PR from bitbucket

### ISSUE THREAD

**Issue by muhrahmatullah** [sshaw/export-pull-requests#12]
I tried to export pr from our bitbucket review but the response said : 410 {"type": "error", "error": {"message": "Resource removed", "detail": "This API is no longer supported.\n\nFor information about its removal, please refer to the deprecation notice at: https://developer.atlassian.com/cloud/bitbucket/deprecation-notice-v1-apis/"}}

I wonder how can I change the api version from 1.0 to 2.0

thank you

**Comment by sshaw** [comment]
I assume this is for the issues endpoint? 

Other calls use v2, not sure why this ones uses v1. [The API client I use](https://github.com/bitbucket-rest-api/bitbucket) hasn't been updated in a while.

> I wonder how can I change the api version from 1.0 to 2.0

Me too...

**Comment by muhrahmatullah** [comment]
thank you for the immediate response, now looking for a workaround on that

**Comment by muhrahmatullah** [comment]
apparently, it happened because I didn't complete the syntax, so initially, I only use epr -p bitbucket -t bitbucket_username:app_password user/repo1 this command,
soon I finished it with -s and -x it works. thank you

**Comment by sshaw** [comment]
Hi, glad to hear you got it working. 

I'm going to reopen this as `epr -p bitbucket -t AUTH user/repo` _should_  export all issue types in all states. At least there's a workaround but I need to investigate.

**Comment by muhrahmatullah** [comment]
Okay got it

**Comment by sshaw** [comment]
Still an issue but closing for the generic #19.
