### ISSUE TITLE
How to export all pull requests and not just open pull requests

### ISSUE THREAD

**Issue by krithigagupta** [sshaw/export-pull-requests#15]
Please let me know how to export all the pull requests from bitbucket and just not the Open PR's.

**Comment by sshaw** [comment]
Looking at Bitbucket issues I see the following: 

<img width="389" alt="Screen Shot 2020-03-24 at 10 21 14 PM" src="https://user-images.githubusercontent.com/17570/77495032-d67f5f00-6e1d-11ea-8314-5ad48d81208b.png">

So I'd try listing out all of these, keeping the space in the status name:

```
epr -p bitbucket -s 'new,open,resolved,on hold,etc...'  your/repo
```

**Comment by krithigagupta** [comment]
Thank you so much. That worked. But in my exported data, I don't see any user id or who created the PR. How do I get those? Thank you so much for this handy tool. It helped me extract the PR’s for multiple repos all at once

**Comment by sshaw** [comment]
>  I don't see any user id or who created the PR. How do I get those? 
Should be there:
https://github.com/sshaw/export-pull-requests/blob/9c9c9b2e275fad3c3ccf7c63ee83ac0fb61938dd/bin/epr#L79

What do you get instead. 


And actually what arguments are **you** using because when I run:

```
epr -t TOKEN -p bitbucket  REPO
```
I get: 

```
410 {"type": "error", "error": {"message": "Resource removed", "detail": "This API is no longer supported.\n\nFor information about its removal, please refer to the deprecation notice at: https://developer.atlassian.com/cloud/bitbucket/deprecation-notice-v1-apis/"}}
```

```
~ >epr -v
v0.3.3 (GitHub v0.18.2, GitLab v4.11.0, Bitbucket v0.1.7)
```

**Comment by sshaw** [comment]
Closing due to lack of feedback. Feel free to reopen with additional info.
