### ISSUE TITLE
Option -e do not works.

### ISSUE THREAD

**Issue by sand1p** [sshaw/export-pull-requests#16]
I want all the Pull Requests for some organization. 
I have tried the command, `epr -e orgs/:org > all_data.csv ` 
Unfortunately, I am receiving an error,  `usage: epr [options] user/repo1 [user/repo2...]`

**Comment by sshaw** [comment]
Hi, the `-e` option is not for organization repositories, it's for custom GitHub (or whoever) hosts. For example: https://github.com/enterprise

To get all the PRs for an organization you will have to list them:

```
epr org/repo1 org/repo2
```
