### ISSUE TITLE
Results do not include PR creators

### ISSUE THREAD

**Issue by divnych** [sshaw/export-pull-requests#20]
Here is the command I'm running:

`epr -p bitbucket -t bitbucket_username:app_password user/repo1 -x pr -s all> pr.csv`

![image](https://user-images.githubusercontent.com/33792604/107671720-d2aa3480-6c9c-11eb-9216-86ae34c3afaf.png)

The resulted table doesn't include any information regarding PR creators
![image](https://user-images.githubusercontent.com/33792604/107672126-3fbdca00-6c9d-11eb-8cf6-3c5142c07288.png)

When I use it with 'creator' option, like `-c 'username'` it returns an empty table.

**Comment by sshaw** [comment]
Yay Bitbucket!

Their 2.0 API removed the `username` property. Try latest master, 0169b01.

**Comment by divnych** [comment]
Thanks for your reply. How am I supposed to pick up the new changes from master? I'm trying to execute `gem update export-pull-requests` and it says nothing to update.

**Comment by sshaw** [comment]
Just made release v0.3.4 with this fix. Try again.
