### ISSUE TITLE
How to use milestone option

### ISSUE THREAD

**Issue by deepres** [sshaw/export-pull-requests#21]
I tried to use it but it doesn't seem to be working - it's exporting all the PRs.

Example. I have a Mainnet milestone where I want to list all the PRs belonging to it. 

`epr -x pr -s closed -m Mainnet CasperLabs/casper-node`

As the output, I get a list of all closed PR's. I tried also -m "Mainnet" and -m="Mainnet"

**Comment by sshaw** [comment]
Hi, the command looks correct **except** for the `-x pr`. On GitHub [milestones only work for issues](https://docs.github.com/en/rest/reference/issues#list-repository-issues). So you can say:

```
epr -s closed -m Mainnet CasperLabs/casper-node
```

Let me know if that works and I'll update the docs :octocat:

**Comment by sshaw** [comment]
> Let me know if that works and I'll update the docs :octocat:

Actually no. I will exit with failure if `-x pr` and `-m` are given.

**Comment by sshaw** [comment]
v0.3.5 will exit with an error if attempting to use milestones with PRs for GitHub. 

If you still need assistance feel free to reopen the issue.
