### ISSUE TITLE
epr does not work on Windows 10

### ISSUE THREAD

**Issue by BartVanderbeke** [sshaw/export-pull-requests#25]
I installed "rubyinstaller-devkit-3.0.1-1-x64" and then installed epr.

C:\Windows\System32>epr --help
E:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/faraday-0.9.2/lib/faraday/options.rb:153:in `new': tried to create Proc object without a block (ArgumentError)
        from E:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/faraday-0.9.2/lib/faraday/options.rb:153:in `memoized'
        from E:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/faraday-0.9.2/lib/faraday/options.rb:234:in `<class:ProxyOptions>'
        from E:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/faraday-0.9.2/lib/faraday/options.rb:216:in `<module:Faraday>'
        from E:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/faraday-0.9.2/lib/faraday/options.rb:1:in `<top (required)>'
        from <internal:E:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:E:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from E:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/faraday-0.9.2/lib/faraday.rb:80:in `block in require_libs'
        from E:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/faraday-0.9.2/lib/faraday.rb:79:in `each'
        from E:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/faraday-0.9.2/lib/faraday.rb:79:in `require_libs'
        from E:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/faraday-0.9.2/lib/faraday.rb:240:in `<module:Faraday>'
        from E:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/faraday-0.9.2/lib/faraday.rb:16:in `<top (required)>'
        from <internal:E:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:E:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from E:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/github_api-0.19.0/lib/github_api.rb:5:in `<top (required)>'
        from <internal:E:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:E:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from E:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/export-pull-requests-0.3.5/bin/epr:8:in `<top (required)>'
        from E:/Ruby30-x64/bin/epr:23:in `load'
        from E:/Ruby30-x64/bin/epr:23:in `<main>'

**Comment by sshaw** [comment]
Hi, thanks for bringing this to my attention. The underlying issue is Ruby 3. 

The simple solution, [install Ruby < 3](https://rubyinstaller.org/2020/10/06/rubyinstaller-2.7.2-1-2.6.6-2-and-2.5.8-2-released.html) and export, export, export!


## Gory Details

This is due to https://github.com/piotrmurach/github/issues/378. Fixing it requires Faraday 1.3 but the ever-problematic Bitbucket API client (#19) depends on Faraday `~> 0.8.1`.

**Comment by sshaw** [comment]
Closing for #26. 

I updated the docs and released 0.3.6 that requires Ruby < 3 to install.

**Comment by sshaw** [comment]
Versions >= 0.4 now support Ruby >= 3.
