### ISSUE TITLE
support modifying config to point to enterprise Github/Gitlab instances

### ISSUE THREAD

**Issue by joshoohaah** [sshaw/export-pull-requests#4]
Is it possible to edit this tool to support pointing to different API endpoints? specifically if i wanted to point this to our internal enterprise Github and Gitlab servers.  I don't see a way currently to configure this tool to point to non-public services.

**Comment by sshaw** [comment]
Just added added a `-e`/`--endpoint` option via 17b6b55cd6e026bc9919fd546e40f1868e9c1b69. Try that and let me know if that works for you.

**Comment by joshoohaah** [comment]
this works great. thanks! yes I saw the hardcoded gitlab reference in your code (on line 173.) . this fixes that.  thank you so much! 👍
