### ISSUE TITLE
Does this also export comments/reviews/conversation?

### ISSUE THREAD

**Issue by rigelrozanski** [sshaw/export-pull-requests#5]

**Comment by sshaw** [comment]
Hi, no it doesn't support this. I'm open to this but I believe I left it out because it currently exports only to spreadsheet which may not be the best format for this.

**Comment by rigelrozanski** [comment]
Thanks

**Comment by cristianrat** [comment]
This is the one feature I actually need and it's not in :D
Any suggestions? Can this be added easily?

**Comment by sshaw** [comment]
> Any suggestions? Can this be added easily?

Yes, can be easily added but how to format? https://api.github.com/repos/sshaw/export-pull-requests/issues/5/comments

Add a column "comments" and repeat all the info on each row for each comment?

**Comment by sshaw** [comment]
|  Repository | Type | # | Comment | Comment Date | Comment By | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
|  export-pull-requests | Issue  | 5 | Some comment here | 2019-01-01 | cristianrat |
|  export-pull-requests | Issue  | 5 | Another amazing comment.... | 2019-01-02 | sshaw |
|  export-pull-requests | Issue  | 5 | Thanks | rigelrozanski | 2019-01-03 |

**Comment by cristianrat** [comment]
@sshaw Thanks for the reply.
My scenario is a bit specific, so what I really need is aprover details (mostly username / email) as a new column. From what I see in the github api, that means an extra API request for each issue / PR
Comments etc. are not relevant to my case.

**Comment by sshaw** [comment]
Ok, so info from here? https://developer.github.com/v3/issues/events/

Everything is possible!

**Comment by cristianrat** [comment]
:) with enough time, money or resources, indeed
Don't think it's that one.
I think it would be this one:
https://developer.github.com/v3/pulls/
And from there I only need the merged_by

**Comment by sshaw** [comment]
@cristianrat, did some research here and GitHub will only return an email address for a user if they [make their email public](https://developer.github.com/v3/users/#get-a-single-user) but, even in the case of [someone that does](https://github.com/sindresorhus) the API _still_ does not return their email: https://api.github.com/users/sindresorhus

Maybe my access token doesn't have the right permissions 🤷‍♂️

What's your experience like getting a user's email?

**Comment by cristianrat** [comment]
Yeah, I noticed that as well
In lieu of email, I'll just use the username, which should suffice :)

**Comment by krishnammv** [comment]
Is this feature not yet available? If not, how to import all the conversation from PR's of the Github Repository

**Comment by sshaw** [comment]
> Is this feature not yet available? 

No. Not yet, at least...

> If not, how to import all the conversation from PR's of the Github Repository

I assume you mean export? Currently the program does not support it. I'd suggest opening a PR 🙏
