### ISSUE TITLE
Latest published gem does not contain most recent bug fixes

### ISSUE THREAD

**Issue by jammaloo** [sshaw/export-pull-requests#7]
Hello, 

First of all thank you for creating this tool, it is very useful!

I did notice that the published gem, installed via `gem install export-pull-requests` throws an error if you pass the `-b` flag to retrieve the body.

`/Library/Ruby/Gems/2.3.0/gems/export-pull-requests-0.2.1/bin/epr:275:in `<top (required)>': invalid option: -b (OptionParser::InvalidOption)`

Cloning the repository and running the binary directly works as expected.

Could you please publish the latest version of the gem?

**Comment by sshaw** [comment]
Hi, yes never published because `-b`only works with GitHub. Was going to add support for others but oh well, someday. 

Nevertheless I've published the latest version: v0.2.2.
