### ISSUE TITLE
Any plans to to export or filter on assignees, labels, milestones?

### ISSUE THREAD

**Issue by cboyden** [sshaw/export-pull-requests#8]
Do you have any plans to add command-line filter options for assignees, labels, or milestones? Or to add this data to the export? Assignees and labels can be multiple, but there can only be one milestone set for an issue.

**Comment by sshaw** [comment]
Hi, I had not planned on it but it's certainly a good idea. Pull requests welcome!

**Comment by sshaw** [comment]
In the spirit of Orthodox Christmas I've added options to filter on labels or milestones: https://github.com/sshaw/export-pull-requests/commit/4dd737b.  🎄🎅

#9 is issue for assignees. Would be great if you can add.

**Comment by sshaw** [comment]
Note that I have not made a release yet. Let me know if options are as desired and then I will release.

**Comment by cboyden** [comment]
This is looking good. I tested filtering on milestones and labels (single and multiple). Works as expected. Milestones are referenced by ID and everything else is reference by name - does that need any explanation in the readme or usage notes?

**Comment by sshaw** [comment]
> ... does that need any explanation in the readme or usage notes?

For milestones I thought about it, but every service may differ so one should expect to provide whatever the service requires. But, if you think some docs are necessary I can add.
